import atexit
import os

import psycopg
from flask import g
from psycopg.rows import dict_row
from psycopg_pool import ConnectionPool

DATABASE_URL = os.environ.get("DATABASE_URL")

SCHEMA = [
    """
    CREATE TABLE IF NOT EXISTS users (
        id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        username TEXT UNIQUE NOT NULL,
        password_hash TEXT NOT NULL,
        full_name TEXT DEFAULT '',
        email TEXT DEFAULT '',
        carrera TEXT DEFAULT '',
        avatar TEXT DEFAULT '',
        theme TEXT DEFAULT 'light',
        created_at TEXT DEFAULT (to_char(CURRENT_TIMESTAMP, 'YYYY-MM-DD HH24:MI:SS'))
    )
    """,
    """
    CREATE TABLE IF NOT EXISTS materias (
        id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
        codigo TEXT DEFAULT '',
        nombre TEXT NOT NULL,
        profesor TEXT DEFAULT '',
        modalidad TEXT DEFAULT 'presencial',
        horas_semana INTEGER DEFAULT 0,
        aula TEXT DEFAULT '',
        comision TEXT DEFAULT '',
        color TEXT DEFAULT 'indigo',
        regimen TEXT DEFAULT 'promocionable',
        created_at TEXT DEFAULT (to_char(CURRENT_TIMESTAMP, 'YYYY-MM-DD HH24:MI:SS'))
    )
    """,
    """
    CREATE TABLE IF NOT EXISTS clases (
        id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
        materia_id INTEGER REFERENCES materias(id) ON DELETE CASCADE,
        dia INTEGER NOT NULL,
        hora_inicio TEXT NOT NULL,
        hora_fin TEXT NOT NULL,
        tipo TEXT DEFAULT 'teorica',
        aula TEXT DEFAULT ''
    )
    """,
    """
    CREATE TABLE IF NOT EXISTS tareas (
        id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
        materia_id INTEGER REFERENCES materias(id) ON DELETE CASCADE,
        titulo TEXT NOT NULL,
        descripcion TEXT DEFAULT '',
        fecha_limite TEXT DEFAULT '',
        prioridad TEXT DEFAULT 'media',
        tipo_entrega TEXT DEFAULT 'individual',
        estado TEXT DEFAULT 'pendiente',
        created_at TEXT DEFAULT (to_char(CURRENT_TIMESTAMP, 'YYYY-MM-DD HH24:MI:SS'))
    )
    """,
    """
    CREATE TABLE IF NOT EXISTS examenes (
        id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
        materia_id INTEGER REFERENCES materias(id) ON DELETE CASCADE,
        nombre TEXT DEFAULT 'Parcial',
        categoria TEXT DEFAULT 'primeros',
        fecha TEXT NOT NULL,
        hora TEXT DEFAULT '08:00',
        aula TEXT DEFAULT ''
    )
    """,
    "CREATE INDEX IF NOT EXISTS idx_materias_user ON materias(user_id)",
    "CREATE INDEX IF NOT EXISTS idx_clases_user ON clases(user_id)",
    "CREATE INDEX IF NOT EXISTS idx_tareas_user ON tareas(user_id)",
    "CREATE INDEX IF NOT EXISTS idx_examenes_user ON examenes(user_id)",
]

_pool = None


def get_pool():
    global _pool
    if _pool is None:
        if not DATABASE_URL:
            raise RuntimeError(
                "DATABASE_URL no está configurada. Definila en el archivo .env "
                "con la cadena de conexión de PostgreSQL (Supabase)."
            )
        _pool = ConnectionPool(
            DATABASE_URL,
            min_size=1,
            max_size=4,
            kwargs={"row_factory": dict_row},
            open=True,
            timeout=30,
        )
        atexit.register(close_pool)
    return _pool


def close_pool():
    global _pool
    if _pool is not None:
        _pool.close()
        _pool = None


def connect():
    if not DATABASE_URL:
        raise RuntimeError(
            "DATABASE_URL no está configurada. Definila en el archivo .env "
            "con la cadena de conexión de PostgreSQL (Supabase)."
        )
    try:
        return get_pool().getconn(timeout=30)
    except psycopg.OperationalError as exc:
        raise RuntimeError(f"No se pudo conectar a PostgreSQL: {exc}") from exc


def put_conn(conn):
    if conn is None:
        return
    try:
        if conn.info.transaction_status != psycopg.pq.TransactionStatus.IDLE:
            conn.rollback()
        get_pool().putconn(conn)
    except psycopg.OperationalError:
        try:
            conn.close()
        except Exception:
            pass


def get_db():
    if "db" not in g:
        g.db = connect()
    return g.db


def close_db(_=None):
    db = g.pop("db", None)
    if db is not None:
        put_conn(db)


def init_db():
    conn = connect()
    try:
        with conn.cursor() as cur:
            for statement in SCHEMA:
                cur.execute(statement)
        conn.commit()
    finally:
        put_conn(conn)


def seed():
    # El seed de datos de demostración se eliminó: creaba el usuario demo
    # "sofia" (demo1234) y sus materias/clases/tareas/exámenes cuando la base
    # estaba vacía. Queda deshabilitado para que la app nunca vuelva a crear
    # la cuenta demo ni datos de prueba. Idempotente y seguro: no modifica
    # datos reales existentes.
    return
